### PR TITLE
Restructure supported decorators, add RuboCop and basic fixes

### LINKED ISSUE #17: Add `Nn_` `p_` `s_` and other combinations to SUPPORTED_DECORATORS
After the discussion in https://github.com/puppetlabs/rubocop-i18n/pull/15 , we found there are quite a few other decorators that it would be good to support such as `Nn_` `p_` and `s_`. We should consider adding those for the next Y release.

### PR DESCRIPTION
**Pull request by highb**
Closes #17

### CODE REVIEW

File: spec/rubocop/cop/i18n/gettext/decorate_function_message_spec.rb [hunk 1]
```diff
@@ -47,15 +47,17 @@
         expect(cop.offenses.size).to eq(0)
       end
     end
-    context "#{function} with the n_ decorator" do
-      it_behaves_like 'a_no_cop_required', "#{function}(n_(\"a string\"))", function
-      it_behaves_like 'a_no_cop_required', "#{function}(n_('a string'))", function
-      it_behaves_like 'a_no_cop_required', "#{function}(CONSTANT, n_('a string'))", function
-      it_behaves_like 'a_no_cop_required', "#{function}(n_(\"a string %{value0}\")) % { value0: var, }", function
+    RuboCop::Cop::I18n::GetText.supported_decorators.each do |decorator|
```
Comment (ericldelaney) [inline spec/rubocop/cop/i18n/gettext/decorate_function_message_spec.rb]: cool

File: spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_interpolation_spec.rb [hunk 2]
```diff
@@ -1,18 +1,18 @@
...
-  }
+  end
 
-  decorators = ['_', 'n_', 'N_']
+  decorators = %w[_ n_ N_]
   decorators.each do |decorator|
-
     context "#{decorator} decoration not used" do
-      it_behaves_like 'a_no_cop_required', "thing(\"a #{true} that is not decorated\")"
+      it_behaves_like 'a_no_cop_required', 'thing("a true that is not decorated")'
```
Comment (ericldelaney) [inline spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_interpolation_spec.rb]: Actually this was verifying that a method name 'thing' that wasn't part of the supported list and had a #{} in a string, wouldn't trigger the cop.

File: spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_percent_spec.rb [hunk 3]
```diff
@@ -1,18 +1,18 @@
...
-  before(:each) {
+  let(:config) { RuboCop::Config.new }
+  subject(:cop) { described_class.new(config) }
+  before(:each) do
     investigate(cop, source)
-  }
+  end
 
-  decorators = ['_', 'n_', 'N_']
+  decorators = %w[_ n_ N_]
```
Comment (ericldelaney) [inline spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_percent_spec.rb]: Remove and use RuboCop::Cop::I18n::GetText.supported_decorators.each ?

File: spec/rubocop/cop/i18n/gettext/decorate_string_spec.rb [hunk 4]
```diff
@@ -1,19 +1,20 @@
 # frozen_string_literal: true
+
 require 'spec_helper'
 
 describe RuboCop::Cop::I18n::GetText::DecorateString do
   let(:config) { RuboCop::Config.new }
   subject(:cop) { described_class.new(config) }
 
   # For some reason, this string isn't considered decorated.
```
Comment (ericldelaney) [inline spec/rubocop/cop/i18n/gettext/decorate_string_spec.rb]: We should remove this

File: rubocop-i18n.gemspec [hunk 5]
```diff
@@ -1,29 +1,32 @@
 # coding: utf-8
+
 lib = File.expand_path('../lib', __FILE__)
 $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
+rubocop_version = '~> 0.49.0'
 
 Gem::Specification.new do |spec|
-  spec.name          = "rubocop-i18n"
+  spec.name          = 'rubocop-i18n'
   spec.version       = '1.1.0'
```
Comment (ericldelaney) [inline rubocop-i18n.gemspec]: when does the version get changed?

File: spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_interpolation_spec.rb (hunk 2 above)
Comment (highb) [reply spec/rubocop/cop/i18n/gettext/decorate_string_formatting_using_interpolation_spec.rb]: Huh, that's an odd thing for the linter to auto-fix. I guess because the # wasn't escaped, it did the auto-fix. I'll switch it back and see what rubocop complains about.
